import type { Metadata } from "next";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
        <EdgeStoreProvider>
        {children}
        </EdgeStoreProvider>
        </NextAuthProvider>
        </body>
    </html>
  );
}
